# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: Deploy personal website
on:
  push:
    paths:
      - "frontend/**"
env:
  BUCKET_NAME: "185284124654-personal-website"
  AWS_REGION: "eu-west-1"
# permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  BuildFrontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install frontend dependencies
        run: yarn workspaces focus frontend
      - name: Build frontend static files
        run: yarn workspace frontend run build
      - name: Archive frotend static files
        uses: actions/upload-artifact@v3
        with:
          name: frontend-out
          path: frontend/out

  S3PackageUpload:
    runs-on: ubuntu-latest
    needs: BuildFrontend
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-out
          path: out
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::185284124654:role/github-oidc-provider-aws
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name: Sync frontend with S3
        run: |
          aws s3 sync $PWD/out s3://${{ env.BUCKET_NAME }}/
